---
- hosts: all
  become: true
  gather_facts: yes

  tasks:
    - name: Install python3 and pip3
      package:
        name:
          - "{{ python_package }}"
          - "{{ pip_package }}"
        state: latest

    - name: Set python3 as default python (Ubuntu)
      command: "ln -sf /usr/bin/python3 /usr/bin/python"
      when: ansible_distribution == 'Ubuntu'

    - name: Set pip3 as default pip (Ubuntu)
      command: "ln -sf /usr/bin/pip3 /usr/bin/pip"
      when: ansible_distribution == 'Ubuntu'

    - name: Set python3 as default python (CentOS)
      command: "ln -sf /usr/bin/python3 /usr/bin/python"
      when: ansible_distribution == 'CentOS'

    - name: Set pip3 as default pip (CentOS)
      command: "ln -sf /usr/bin/pip3 /usr/bin/pip"
      when: ansible_distribution == 'CentOS'

    - name: Install Java OpenJDK
      package:
        name: "{{ java_package }}"
        state: latest

    - name: Create motd file
      template:
        src: motd.j2
        dest: /etc/motd

    - name: Ensure new user exists
      user:
        name: "{{ new_user }}"
        state: present
